version: '2'
services:
  cadvisor:
    image: google/cadvisor:v0.24.1
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus:v1.2.1
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
