global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:

rule_files:

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'container'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
